# Generated by Django 3.0.8 on 2020-08-25 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200824_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow_users',
        ),
        migrations.AddField(
            model_name='user',
            name='follow_users',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
